Portafolios/Portafolios/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('usuarios/', include('usuarios.urls')),
]

Portafolios/core/urls.py
from django.urls import path
from . import views

app_name ='core'

urlpatterns = [
   path('', views.index, name='index'),
   path('perfil/', views.perfil, name='perfil'),
   path('reservar_hora/', views.reserva_de_hora, name='reserva_de_hora'),

]

Portafolios/usuarios/urls.py
from django.urls import path
from . import views

app_name='usuarios'

urlpatterns = [
    path('register/',views.register, name='registro'),
    path('login/',views.login, name='inicio_sesion'),
    path('logout/',views.logout, name='cerrar_sesion'),    
]

Portafolios/core/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from usuarios.models import UsuarioWeb
from django.db import models
from django.contrib.auth.models import AbstractUser


class Boleta(models.Model):
    id = models.BigAutoField(primary_key=True)
    servicio = models.ForeignKey('Servicio', on_delete=models.CASCADE)
    fecha = models.DateTimeField()
    comentario = models.CharField(max_length=100, blank=True, null=True)
    total = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'boleta'


class Reservadehora(models.Model):
    id = models.BigAutoField(primary_key=True)
    fecha_solicitud = models.DateTimeField()
    asunto = models.CharField(max_length=200)
    tiposervicio = models.ForeignKey('Tiposervicio', on_delete=models.CASCADE)
    usuarioescritorio = models.ForeignKey('Usuarioescritorio', on_delete=models.CASCADE)
    usuarioweb = models.ForeignKey(UsuarioWeb, on_delete=models.CASCADE)

    class Meta:
        managed = True
        db_table = 'reservadehora'


class Servicio(models.Model):
    id = models.BigAutoField(primary_key=True)
    fecha = models.DateTimeField()
    comentario = models.CharField(max_length=200, blank=True, null=True)
    validado = models.BooleanField()
    reservadehora = models.ForeignKey(Reservadehora, on_delete=models.CASCADE)
    

    class Meta:
        managed = False
        db_table = 'servicio'


class Tiposervicio(models.Model):
    id = models.BigAutoField(primary_key=True)
    descripcion = models.CharField(max_length=100)
    precio = models.IntegerField()

    def __str__(self):
        return self.descripcion

    class Meta:
        managed = False
        db_table = 'tiposervicio'


class Tipousuario(models.Model):
    id = models.BigAutoField(primary_key=True)
    descripcion = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'tipousuario'


class Usuarioescritorio(models.Model):
    id = models.BigAutoField(primary_key=True)
    tipousuario = models.ForeignKey(Tipousuario, on_delete=models.CASCADE)
    nombre_usuario = models.CharField(max_length=100)
    contrasena = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    primer_nombre = models.CharField(max_length=150)
    segundo_nombre = models.CharField(max_length=150, blank=True, null=True)
    apellido_paterno = models.CharField(max_length=150)
    apellido_materno = models.CharField(max_length=150)
    rut = models.IntegerField()
    dv = models.CharField(max_length=1)
    fecha_nacimiento = models.DateField()

    def __str__(self):
        nombre = self.primer_nombre + ' ' + self.apellido_paterno + ' ' + self.apellido_materno
        return nombre

    class Meta:
        managed = False
        db_table = 'usuarioescritorio'

Portafolios/core/forms.py
from django import forms
from django.forms import widgets
from django.forms.models import fields_for_model
from .models import Reservadehora, Usuarioescritorio

class ReservadeHoraForm(forms.ModelForm):
    asunto = forms.CharField(widget=forms.Textarea(attrs={'rows':4}))
    hora = forms.CharField()
    class Meta:
        model = Reservadehora
        fields = ('fecha_solicitud','asunto','tiposervicio','usuarioescritorio')
    
    def __init__(self, *args, **kwargs):

        super(ReservadeHoraForm, self).__init__(*args,**kwargs)
        self.fields['usuarioescritorio'] = forms.ModelChoiceField(queryset=Usuarioescritorio.objects.filter(tipousuario_id=1))

        for field in self.fields:
            
            self.fields[field].widget.attrs.update({'class': 'form-control'})
            self.fields[field].widget.attrs.update({'autocomplete': 'off'})

        self.fields['hora'].widget.attrs.update({'class': 'form-control timepicker'})        

Portafolios/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import ReservadeHoraForm
from django.db import connection
from .models import Reservadehora

def index(request):

    return render(request,'core/index.html',{})

@login_required(login_url='/usuarios/login/')
def reserva_de_hora(request):

    form_reserva = ReservadeHoraForm()

    if request.method == 'POST':
        
        form_reserva = ReservadeHoraForm(data=request.POST)

        if form_reserva.is_valid():

            fecha_solicitud = form_reserva.data['fecha_solicitud']
            hora = form_reserva.data['hora']
            asunto = form_reserva.data['asunto']
            tiposervicio = form_reserva.data['tiposervicio']
            usuarioescritorio = form_reserva.data['usuarioescritorio']
            usuarioweb = request.user.id
            print(request.user.id)
            print(fecha_solicitud)
            print(hora)
            fecha = fecha_solicitud + ' ' + hora
            print(fecha)


            with connection.cursor() as cursor:
                cursor.callproc('PKG_RESERVADEHORA.PR_AGREGAR_RESERVADEHORA',[fecha,asunto,tiposervicio,usuarioescritorio,usuarioweb])
            
            return redirect('core:index')


    return render(request,'core/reserva_de_hora.html',{'form':form_reserva})

@login_required(login_url='/usuarios/login/')
def perfil(request):

    return render(request,'core/perfil.html',{})

Portafolios/core/templates/core/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Inicio</title>
{% endblock head %}
{% block content %}
        <header class="masthead">

        </header>
        <!-- About-->
        <section class="mastsection about-section text-center" id="about">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <h2 class="text-white mb-4">¿Quienes Somos?</h2>
                        <p class="text-white-80">
                        Aquí no hay estafas. Solo hay trabajo e ingeniería de calidad para tu vehiculo.
                        Aquí en Servi Express ponemos a tu vehiculo de pie por un precio razonable. No vamos a llevar a cabo
                         trabajos importantes sin hablar contigo primero. Es más, nuestro servicio rápido significa que tu vehiculo y
                          la carretera estarán unidos de nuevo en poco tiempo. Para saber más, o para reservar una consulta en Santiago o 
                          póngase en contacto con nosotros en el formulario
                        </p>
                    </div>
                </div>
            </div>
        </section>
        <!-- Projects-->
        <section class="projects-section" id="projects">
        </section>
        <!-- Signup-->
    {% if user.is_authenticated %}
    {% else %}       
        <section class="signup-section" id="signup">
            <div class="container">
                <div class="row">
                    <div class="col-md-10 col-lg-8 mx-auto text-center">
                        <i class="far fa-paper-plane fa-2x mb-2 text-white"></i>
                        <h2 class="text-white mb-2">Registrate Aquí</h2>
                        <p class="text-white">o inicia sesión</p>
                        <div class="inline d-flex">
                            <button class="btn btn-primary mx-auto" type="button" onclick="location.href='{% url 'usuarios:registro' %}'">Registrarse</button>
                                                        <button class="btn btn-primary mx-auto" type="button" onclick="location.href='{% url 'usuarios:inicio_sesion' %}'">Inicia Sesion</button>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    {% endif %}
{% endblock content %}

Portafolios/core/templates/core/perfil.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <title>Perfil</title>
{% endblock head %}
{% block content %}
{% endblock content %}

Portafolios/core/templates/core/reserva_de_hora.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <title>Reserva de Hora</title>
{% endblock head %}
{% block content %}
        <header class="masthead">
        <br>        <br>
            <div class="container"> <div class=" text-center mt-5 ">
                </div>
                <div class="row ">
                    <div class="col-lg-7 mx-auto">
                        <div class="card mt-2 mx-auto p-4 bg-light">
                            <div class="card-body bg-light">
                                <div class="container">
                                    <form role="form" method="POST">
                                        {% csrf_token %}
                                        <div class="controls">
                                            <div class="row">
                                                <div class="col-md-4">
                                                    <div class="form-group">{{form.fecha_solicitud.label}} {{form.fecha_solicitud}} {{form.fecha_solicitud.errors}}</div>
                                                </div>
                                                <div class="col-md-3">
                                                    <div class="form-group">{{form.hora.label}} {{form.hora}} {{form.hora.errors}}</div>
                                                </div>
                                                <div class="col-md-2">
                                                    <div> <input type="button" class="btn btn-primary" value="Validar Hora"> </div>
                                                </div>                                                                                             
                                                <div class="col-md-8">
                                                    <div class="form-group">Servicio {{form.tiposervicio}} {{form.tiposervicio.errors}}</div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">Mecanico {{form.usuarioescritorio}} {{form.usuarioescritorio.errors}}</div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">{{form.asunto.label}} {{form.asunto}} {{form.asunto.errors}}</div>
                                                </div>
                                            </div>                                            

                                                <div class="col-md-12 d-flex justify-content-center"> <input type="submit" class="btn btn-primary" value="Registrar Hora"> </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div> <!-- /.8 -->
                    </div> <!-- /.row-->
                </div>
            </div>
        </header>
        <script>
            $(function () {
            $("#id_fecha_solicitud").datepicker({
                format:'dd/mm/yyyy',
            });
            });
        </script>
        <script>
            $(function () {
            $('#id_hora').timepicker({
                timeFormat: 'HH:mm',
                interval: 15,
                minTime: '9:00am',
                maxTime: '8:45pm',
                defaultTime: '9:00am',
                startTime: '10:00',
                dynamic: true,
                dropdown: true,
                scrollbar: true
            });
            });
        </script>
<section class='container'>
{% endblock content %}