Portafolios/Portafolios/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('usuarios/', include('usuarios.urls')),
]

Portafolios/core/urls.py
from django.urls import path
from . import views

app_name ='core'

urlpatterns = [
   path('', views.index, name='index'),
   path('perfil/', views.perfil, name='perfil'),
   path('reservar_hora/', views.reserva_de_hora, name='reserva_de_hora'),

]

Portafolios/usuarios/urls.py
from django.urls import path
from . import views

app_name='usuarios'

urlpatterns = [
    path('register/',views.register, name='registro'),
    path('login/',views.login, name='inicio_sesion'),
    path('logout/',views.logout, name='cerrar_sesion'),    
]

Portafolios/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class UsuarioWeb(AbstractUser):

    fecha_nacimiento    = models.DateField(verbose_name='fecha de nacimiento', null=True) 

    class Meta:
        managed = True
        db_table = 'usuarioweb'

Portafolios/usuarios/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import widgets
from django.forms.models import fields_for_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import UsuarioWeb

class RegistrationForm(UserCreationForm):

    first_name = forms.CharField(label='Nombre',required=True)
    last_name = forms.CharField(label='Apellidos',required=True)
    email = forms.EmailField(required=True)

    def clean_email(self):
        email = self.cleaned_data['email']
        if UsuarioWeb.objects.filter(email=email).exists():
            raise ValidationError("Ya exsite un usuario con este Email.")
        return email    

    class Meta:

        model = UsuarioWeb
        fields = ('username','first_name' ,'last_name' , 'email', 'password1', 'password2', 'fecha_nacimiento') 

    def __init__(self, *args, **kwargs):

        super(RegistrationForm, self).__init__(*args,**kwargs)


        for field in self.fields:
            
            self.fields[field].widget.attrs.update({'class': 'form-control'})
            self.fields[field].widget.attrs.update({'autocomplete': 'off'})

 
        for field in self.fields.values():
                field.help_text = None

class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):

        super(LoginForm, self).__init__(*args,**kwargs)

        for field in self.fields:
            
            self.fields[field].widget.attrs.update({'class': 'form-control'})
            self.fields[field].widget.attrs.update({'autocomplete': 'off'})    

Portafolios/usuarios/views.py
from django.shortcuts import render, redirect
from django.http.response import HttpResponse, HttpResponseRedirect
from .forms import RegistrationForm, LoginForm
from django.contrib.auth import login as log_in, logout as log_out
from .auth import AuthenticationEmailBackend
from django.contrib.auth import authenticate
from usuarios.models import UsuarioWeb

def register(request):

    registration_form = RegistrationForm()

    if request.method == "POST":

        registration_form = RegistrationForm(data=request.POST)

        if registration_form.is_valid():

            user = registration_form.save()

            username = registration_form.cleaned_data['username']
            password = registration_form.cleaned_data['password1']

            user = authenticate(username=username,password=password)

            if user is not None:

                log_in(request, user)

                return redirect('core:index')


    return render(request, "usuarios/register.html", {'registration_form': registration_form})

def login(request):

    login_form = LoginForm()

    if request.method == "POST":
        print('pasa')
        login_form = LoginForm(data=request.POST)

        print(login_form.is_valid())
        if login_form.is_valid():

            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']

            user = authenticate(username=username, password=password)

            if user is not None:

                log_in(request, user)

                return redirect('core:index')

            user = AuthenticationEmailBackend(username=username, password=password)

            if user is not None:

                log_in(request, user)

                return redirect('core:index')

    return render(request, 'usuarios/login.html',{'login_form':login_form})

def logout(request):

    log_out(request)

    return redirect('core:index')

Portafolios/usuarios/templates/usuarios/login.html
{% extends "base.html" %}

{% block head %}
<title>
    Inicio de Sesion
</title>
{% endblock head %}

{% block content %}

        <header class="masthead">
        <br>        <br>
            <div class="container"> <div class=" text-center mt-5 ">
                </div>
                <div class="row ">
                    <div class="col-lg-7 mx-auto">
                        <div class="card mt-2 mx-auto p-4 bg-light">
                            <div class="card-body bg-light">
                                <div class="container">
                                    <form role="form" method="POST">
                                        {% csrf_token %}
                                        <div class="controls">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">Usuario o Correo Electronico  {{login_form.username}}</div>
                                                </div>
                                            </div>
                                        
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">{{login_form.password.label}}{{login_form.password}}</div>
                                                </div>                                            
                                            </div>
                                                        {% if login_form.errors %}
                                                <div class="col-md-12 d-flex justify-content-center alert alert-danger" role="alert"> Usuario o Contraseña incorrectos. </div>
                                                        {% endif %}

                                                <div class="col-md-12 d-flex justify-content-center"> <input type="submit" class="btn btn-primary" value="Iniciar Sesion"> </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div> <!-- /.8 -->
                    </div> <!-- /.row-->
                </div>
            </div>
        </header>
<section class='container'>


{% endblock %}

Portafolios/usuarios/templates/usuarios/register.html
{% extends "base.html" %}

{% block head %}
<title>
    Registro de Usuario
</title>
{% endblock head %}

{% block content %}
{% if registration_form.non_field_errors %}
    <div class="aler alert-danger" role="alert">
    {% for error in registration_form.non_field_errors %}
        {{error}}
    {% endfor %}
{% endif %}

        <div class="masthead">
        <br>        <br>
            <div class="container"> <div class=" text-center mt-5 ">
                </div>
                <div class="row ">
                    <div class="col-lg-7 mx-auto">
                        <div class="card mt-2 mx-auto p-4 bg-light">
                            <div class="card-body bg-light">
                                <div class="container">
                                    <form role="form" method="POST">
                                        {% csrf_token %}
                                        <div class="controls">
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">{{registration_form.username.label}}  {{registration_form.username}} {{registration_form.username.errors}}</div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">{{registration_form.email.label}}  {{registration_form.email}} {{registration_form.email.errors}}</div>
                                                </div>
                                            </div>
                                        
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">{{registration_form.fecha_nacimiento.label}}  {{registration_form.fecha_nacimiento}} {{registration_form.fecha_nacimiento.errors}}</div>
                                                </div>                                           
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">{{registration_form.first_name.label}} {{registration_form.first_name}} {{registration_form.first_name.errors}}</div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">{{registration_form.last_name.label}} {{registration_form.last_name}} {{registration_form.last_name.errors}}</div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">{{registration_form.password1.label}} {{registration_form.password1}} {{registration_form.password1.errors}}</div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">{{registration_form.password2.label}} {{registration_form.password2}}</div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="form-group">{{registration_form.password2.errors}}</div>
                                                </div>

                                                <div class="col-md-12 d-flex justify-content-center"> <input type="submit" class="btn btn-primary" value="Registrarse"> </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div> <!-- /.8 -->
                    </div> <!-- /.row-->
                </div>
            </div>
        </div>
        <script>
            $(function () {
            $("#id_fecha_nacimiento").datepicker({
                format:'dd/mm/yyyy',
            });
            });
        </script>
<section class='container'>


{% endblock %}